### ISSUE TITLE
Please consider adding license

### ISSUE THREAD

**Issue by asmith26** [kevinzakka/robopianist-rl#1]
Hi there,

Thanks for this amazing research and code. I've been particularly looking into learning more about [DroQ](https://openreview.net/forum?id=xCVJMsPv3RT) which [this research](https://openreview.net/pdf?id=HDYMjiukjn) makes use of, and this looks like a really clean and efficient implementation.

If I am able to understand this, I just thought I'd check if I'm OK to use this with any of my own projects, in particular please can you consider adding a suitable license for this repo (see e.g. https://choosealicense.com/no-permission/)

Many thanks again!

**Comment by kevinzakka** [comment]
Hi @asmith26, added a license. Thanks for the kind words!
